export {default as DashboardIcon } from './dashboard'
// export {default as MoneyIcon } from './money'
export {default as UserIcon } from './users'
export {default as VerificationIcon } from './verify'
export {default as WalletIcon } from './wallet'
export {default as SettingIcon } from './setting'
export {default as PaymentIcon} from './payments'