// import BeIcon from './beicon'

export {default as DashboardIcon } from './dashboard'
// export {default as MoneyIcon } from './money'
export {default as UserIcon } from './users'
export {default as VerificationIcon } from './verify'
export {default as WalletIcon } from './wallet'
export {default as SettingIcon } from './setting'
export {default as PaymentIcon} from './payments'
export {default as StatsIcon } from './stats'
export {default as BellIcon } from './bellicon'
export {default as BeIcon } from './beicon'
export {default as Icon } from './icon'
export {default as MenuOpenIcon } from './menueopenicon'
export {default as MenuCloseIcon } from './menucloseicon'